// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: protobuf_AxibugEmuSnapshot.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace AxibugProtobuf {

  /// <summary>Holder for reflection information generated from protobuf_AxibugEmuSnapshot.proto</summary>
  public static partial class ProtobufAxibugEmuSnapshotReflection {

    #region Descriptor
    /// <summary>File descriptor for protobuf_AxibugEmuSnapshot.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ProtobufAxibugEmuSnapshotReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiBwcm90b2J1Zl9BeGlidWdFbXVTbmFwc2hvdC5wcm90bxIOQXhpYnVnUHJv",
            "dG9idWYi7QEKFnBiX0F4aUVzc2dzc1N0YXR1c0RhdGESQwoKTWVtYmVyRGF0",
            "YRgBIAMoCzIvLkF4aWJ1Z1Byb3RvYnVmLnBiX0F4aUVzc2dzc1N0YXR1c0Rh",
            "dGFfQnl0ZURhdGESSQoRQXJyYXkyRE1lbWJlckRhdGEYAiADKAsyLi5BeGli",
            "dWdQcm90b2J1Zi5wYl9BeGlFc3Nnc3NTdGF0dXNEYXRhXzJEQXJyYXkSQwoJ",
            "Q2xhc3NEYXRhGAMgAygLMjAuQXhpYnVnUHJvdG9idWYucGJfQXhpRXNzZ3Nz",
            "U3RhdHVzRGF0YV9DbGFzc0RhdGEiPwofcGJfQXhpRXNzZ3NzU3RhdHVzRGF0",
            "YV9CeXRlRGF0YRIPCgdLZXlOYW1lGAEgASgJEgsKA1JhdxgCIAEoDCJaCh5w",
            "Yl9BeGlFc3Nnc3NTdGF0dXNEYXRhXzJEQXJyYXkSDwoHS2V5TmFtZRgBIAEo",
            "CRIMCgRyb3dzGAIgASgFEgwKBGNvbHMYAyABKAUSCwoDUmF3GAQgASgMIm4K",
            "IHBiX0F4aUVzc2dzc1N0YXR1c0RhdGFfQ2xhc3NEYXRhEg8KB0tleU5hbWUY",
            "ASABKAkSOQoJY2xhc3NEYXRhGAIgASgLMiYuQXhpYnVnUHJvdG9idWYucGJf",
            "QXhpRXNzZ3NzU3RhdHVzRGF0YUICSAFiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::AxibugProtobuf.pb_AxiEssgssStatusData), global::AxibugProtobuf.pb_AxiEssgssStatusData.Parser, new[]{ "MemberData", "Array2DMemberData", "ClassData" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::AxibugProtobuf.pb_AxiEssgssStatusData_ByteData), global::AxibugProtobuf.pb_AxiEssgssStatusData_ByteData.Parser, new[]{ "KeyName", "Raw" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::AxibugProtobuf.pb_AxiEssgssStatusData_2DArray), global::AxibugProtobuf.pb_AxiEssgssStatusData_2DArray.Parser, new[]{ "KeyName", "Rows", "Cols", "Raw" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::AxibugProtobuf.pb_AxiEssgssStatusData_ClassData), global::AxibugProtobuf.pb_AxiEssgssStatusData_ClassData.Parser, new[]{ "KeyName", "ClassData" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class pb_AxiEssgssStatusData : pb::IMessage<pb_AxiEssgssStatusData>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<pb_AxiEssgssStatusData> _parser = new pb::MessageParser<pb_AxiEssgssStatusData>(() => new pb_AxiEssgssStatusData());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<pb_AxiEssgssStatusData> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::AxibugProtobuf.ProtobufAxibugEmuSnapshotReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pb_AxiEssgssStatusData() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pb_AxiEssgssStatusData(pb_AxiEssgssStatusData other) : this() {
      memberData_ = other.memberData_.Clone();
      array2DMemberData_ = other.array2DMemberData_.Clone();
      classData_ = other.classData_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pb_AxiEssgssStatusData Clone() {
      return new pb_AxiEssgssStatusData(this);
    }

    /// <summary>Field number for the "MemberData" field.</summary>
    public const int MemberDataFieldNumber = 1;
    private static readonly pb::FieldCodec<global::AxibugProtobuf.pb_AxiEssgssStatusData_ByteData> _repeated_memberData_codec
        = pb::FieldCodec.ForMessage(10, global::AxibugProtobuf.pb_AxiEssgssStatusData_ByteData.Parser);
    private readonly pbc::RepeatedField<global::AxibugProtobuf.pb_AxiEssgssStatusData_ByteData> memberData_ = new pbc::RepeatedField<global::AxibugProtobuf.pb_AxiEssgssStatusData_ByteData>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::AxibugProtobuf.pb_AxiEssgssStatusData_ByteData> MemberData {
      get { return memberData_; }
    }

    /// <summary>Field number for the "Array2DMemberData" field.</summary>
    public const int Array2DMemberDataFieldNumber = 2;
    private static readonly pb::FieldCodec<global::AxibugProtobuf.pb_AxiEssgssStatusData_2DArray> _repeated_array2DMemberData_codec
        = pb::FieldCodec.ForMessage(18, global::AxibugProtobuf.pb_AxiEssgssStatusData_2DArray.Parser);
    private readonly pbc::RepeatedField<global::AxibugProtobuf.pb_AxiEssgssStatusData_2DArray> array2DMemberData_ = new pbc::RepeatedField<global::AxibugProtobuf.pb_AxiEssgssStatusData_2DArray>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::AxibugProtobuf.pb_AxiEssgssStatusData_2DArray> Array2DMemberData {
      get { return array2DMemberData_; }
    }

    /// <summary>Field number for the "ClassData" field.</summary>
    public const int ClassDataFieldNumber = 3;
    private static readonly pb::FieldCodec<global::AxibugProtobuf.pb_AxiEssgssStatusData_ClassData> _repeated_classData_codec
        = pb::FieldCodec.ForMessage(26, global::AxibugProtobuf.pb_AxiEssgssStatusData_ClassData.Parser);
    private readonly pbc::RepeatedField<global::AxibugProtobuf.pb_AxiEssgssStatusData_ClassData> classData_ = new pbc::RepeatedField<global::AxibugProtobuf.pb_AxiEssgssStatusData_ClassData>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::AxibugProtobuf.pb_AxiEssgssStatusData_ClassData> ClassData {
      get { return classData_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as pb_AxiEssgssStatusData);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(pb_AxiEssgssStatusData other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!memberData_.Equals(other.memberData_)) return false;
      if(!array2DMemberData_.Equals(other.array2DMemberData_)) return false;
      if(!classData_.Equals(other.classData_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= memberData_.GetHashCode();
      hash ^= array2DMemberData_.GetHashCode();
      hash ^= classData_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      memberData_.WriteTo(output, _repeated_memberData_codec);
      array2DMemberData_.WriteTo(output, _repeated_array2DMemberData_codec);
      classData_.WriteTo(output, _repeated_classData_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      memberData_.WriteTo(ref output, _repeated_memberData_codec);
      array2DMemberData_.WriteTo(ref output, _repeated_array2DMemberData_codec);
      classData_.WriteTo(ref output, _repeated_classData_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += memberData_.CalculateSize(_repeated_memberData_codec);
      size += array2DMemberData_.CalculateSize(_repeated_array2DMemberData_codec);
      size += classData_.CalculateSize(_repeated_classData_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb_AxiEssgssStatusData other) {
      if (other == null) {
        return;
      }
      memberData_.Add(other.memberData_);
      array2DMemberData_.Add(other.array2DMemberData_);
      classData_.Add(other.classData_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            memberData_.AddEntriesFrom(input, _repeated_memberData_codec);
            break;
          }
          case 18: {
            array2DMemberData_.AddEntriesFrom(input, _repeated_array2DMemberData_codec);
            break;
          }
          case 26: {
            classData_.AddEntriesFrom(input, _repeated_classData_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            memberData_.AddEntriesFrom(ref input, _repeated_memberData_codec);
            break;
          }
          case 18: {
            array2DMemberData_.AddEntriesFrom(ref input, _repeated_array2DMemberData_codec);
            break;
          }
          case 26: {
            classData_.AddEntriesFrom(ref input, _repeated_classData_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class pb_AxiEssgssStatusData_ByteData : pb::IMessage<pb_AxiEssgssStatusData_ByteData>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<pb_AxiEssgssStatusData_ByteData> _parser = new pb::MessageParser<pb_AxiEssgssStatusData_ByteData>(() => new pb_AxiEssgssStatusData_ByteData());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<pb_AxiEssgssStatusData_ByteData> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::AxibugProtobuf.ProtobufAxibugEmuSnapshotReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pb_AxiEssgssStatusData_ByteData() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pb_AxiEssgssStatusData_ByteData(pb_AxiEssgssStatusData_ByteData other) : this() {
      keyName_ = other.keyName_;
      raw_ = other.raw_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pb_AxiEssgssStatusData_ByteData Clone() {
      return new pb_AxiEssgssStatusData_ByteData(this);
    }

    /// <summary>Field number for the "KeyName" field.</summary>
    public const int KeyNameFieldNumber = 1;
    private string keyName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string KeyName {
      get { return keyName_; }
      set {
        keyName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Raw" field.</summary>
    public const int RawFieldNumber = 2;
    private pb::ByteString raw_ = pb::ByteString.Empty;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pb::ByteString Raw {
      get { return raw_; }
      set {
        raw_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as pb_AxiEssgssStatusData_ByteData);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(pb_AxiEssgssStatusData_ByteData other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (KeyName != other.KeyName) return false;
      if (Raw != other.Raw) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (KeyName.Length != 0) hash ^= KeyName.GetHashCode();
      if (Raw.Length != 0) hash ^= Raw.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (KeyName.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(KeyName);
      }
      if (Raw.Length != 0) {
        output.WriteRawTag(18);
        output.WriteBytes(Raw);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (KeyName.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(KeyName);
      }
      if (Raw.Length != 0) {
        output.WriteRawTag(18);
        output.WriteBytes(Raw);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (KeyName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(KeyName);
      }
      if (Raw.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(Raw);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb_AxiEssgssStatusData_ByteData other) {
      if (other == null) {
        return;
      }
      if (other.KeyName.Length != 0) {
        KeyName = other.KeyName;
      }
      if (other.Raw.Length != 0) {
        Raw = other.Raw;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            KeyName = input.ReadString();
            break;
          }
          case 18: {
            Raw = input.ReadBytes();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            KeyName = input.ReadString();
            break;
          }
          case 18: {
            Raw = input.ReadBytes();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class pb_AxiEssgssStatusData_2DArray : pb::IMessage<pb_AxiEssgssStatusData_2DArray>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<pb_AxiEssgssStatusData_2DArray> _parser = new pb::MessageParser<pb_AxiEssgssStatusData_2DArray>(() => new pb_AxiEssgssStatusData_2DArray());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<pb_AxiEssgssStatusData_2DArray> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::AxibugProtobuf.ProtobufAxibugEmuSnapshotReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pb_AxiEssgssStatusData_2DArray() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pb_AxiEssgssStatusData_2DArray(pb_AxiEssgssStatusData_2DArray other) : this() {
      keyName_ = other.keyName_;
      rows_ = other.rows_;
      cols_ = other.cols_;
      raw_ = other.raw_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pb_AxiEssgssStatusData_2DArray Clone() {
      return new pb_AxiEssgssStatusData_2DArray(this);
    }

    /// <summary>Field number for the "KeyName" field.</summary>
    public const int KeyNameFieldNumber = 1;
    private string keyName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string KeyName {
      get { return keyName_; }
      set {
        keyName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "rows" field.</summary>
    public const int RowsFieldNumber = 2;
    private int rows_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Rows {
      get { return rows_; }
      set {
        rows_ = value;
      }
    }

    /// <summary>Field number for the "cols" field.</summary>
    public const int ColsFieldNumber = 3;
    private int cols_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Cols {
      get { return cols_; }
      set {
        cols_ = value;
      }
    }

    /// <summary>Field number for the "Raw" field.</summary>
    public const int RawFieldNumber = 4;
    private pb::ByteString raw_ = pb::ByteString.Empty;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pb::ByteString Raw {
      get { return raw_; }
      set {
        raw_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as pb_AxiEssgssStatusData_2DArray);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(pb_AxiEssgssStatusData_2DArray other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (KeyName != other.KeyName) return false;
      if (Rows != other.Rows) return false;
      if (Cols != other.Cols) return false;
      if (Raw != other.Raw) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (KeyName.Length != 0) hash ^= KeyName.GetHashCode();
      if (Rows != 0) hash ^= Rows.GetHashCode();
      if (Cols != 0) hash ^= Cols.GetHashCode();
      if (Raw.Length != 0) hash ^= Raw.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (KeyName.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(KeyName);
      }
      if (Rows != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Rows);
      }
      if (Cols != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(Cols);
      }
      if (Raw.Length != 0) {
        output.WriteRawTag(34);
        output.WriteBytes(Raw);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (KeyName.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(KeyName);
      }
      if (Rows != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Rows);
      }
      if (Cols != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(Cols);
      }
      if (Raw.Length != 0) {
        output.WriteRawTag(34);
        output.WriteBytes(Raw);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (KeyName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(KeyName);
      }
      if (Rows != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Rows);
      }
      if (Cols != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Cols);
      }
      if (Raw.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(Raw);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb_AxiEssgssStatusData_2DArray other) {
      if (other == null) {
        return;
      }
      if (other.KeyName.Length != 0) {
        KeyName = other.KeyName;
      }
      if (other.Rows != 0) {
        Rows = other.Rows;
      }
      if (other.Cols != 0) {
        Cols = other.Cols;
      }
      if (other.Raw.Length != 0) {
        Raw = other.Raw;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            KeyName = input.ReadString();
            break;
          }
          case 16: {
            Rows = input.ReadInt32();
            break;
          }
          case 24: {
            Cols = input.ReadInt32();
            break;
          }
          case 34: {
            Raw = input.ReadBytes();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            KeyName = input.ReadString();
            break;
          }
          case 16: {
            Rows = input.ReadInt32();
            break;
          }
          case 24: {
            Cols = input.ReadInt32();
            break;
          }
          case 34: {
            Raw = input.ReadBytes();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class pb_AxiEssgssStatusData_ClassData : pb::IMessage<pb_AxiEssgssStatusData_ClassData>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<pb_AxiEssgssStatusData_ClassData> _parser = new pb::MessageParser<pb_AxiEssgssStatusData_ClassData>(() => new pb_AxiEssgssStatusData_ClassData());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<pb_AxiEssgssStatusData_ClassData> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::AxibugProtobuf.ProtobufAxibugEmuSnapshotReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pb_AxiEssgssStatusData_ClassData() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pb_AxiEssgssStatusData_ClassData(pb_AxiEssgssStatusData_ClassData other) : this() {
      keyName_ = other.keyName_;
      classData_ = other.classData_ != null ? other.classData_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pb_AxiEssgssStatusData_ClassData Clone() {
      return new pb_AxiEssgssStatusData_ClassData(this);
    }

    /// <summary>Field number for the "KeyName" field.</summary>
    public const int KeyNameFieldNumber = 1;
    private string keyName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string KeyName {
      get { return keyName_; }
      set {
        keyName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "classData" field.</summary>
    public const int ClassDataFieldNumber = 2;
    private global::AxibugProtobuf.pb_AxiEssgssStatusData classData_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::AxibugProtobuf.pb_AxiEssgssStatusData ClassData {
      get { return classData_; }
      set {
        classData_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as pb_AxiEssgssStatusData_ClassData);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(pb_AxiEssgssStatusData_ClassData other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (KeyName != other.KeyName) return false;
      if (!object.Equals(ClassData, other.ClassData)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (KeyName.Length != 0) hash ^= KeyName.GetHashCode();
      if (classData_ != null) hash ^= ClassData.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (KeyName.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(KeyName);
      }
      if (classData_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(ClassData);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (KeyName.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(KeyName);
      }
      if (classData_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(ClassData);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (KeyName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(KeyName);
      }
      if (classData_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ClassData);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb_AxiEssgssStatusData_ClassData other) {
      if (other == null) {
        return;
      }
      if (other.KeyName.Length != 0) {
        KeyName = other.KeyName;
      }
      if (other.classData_ != null) {
        if (classData_ == null) {
          ClassData = new global::AxibugProtobuf.pb_AxiEssgssStatusData();
        }
        ClassData.MergeFrom(other.ClassData);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            KeyName = input.ReadString();
            break;
          }
          case 18: {
            if (classData_ == null) {
              ClassData = new global::AxibugProtobuf.pb_AxiEssgssStatusData();
            }
            input.ReadMessage(ClassData);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            KeyName = input.ReadString();
            break;
          }
          case 18: {
            if (classData_ == null) {
              ClassData = new global::AxibugProtobuf.pb_AxiEssgssStatusData();
            }
            input.ReadMessage(ClassData);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
